/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.39
 * Generated at: 2020-12-13 12:05:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class lisaaAsiakas_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<script src=\"scripts/main.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/style.css\">\r\n");
      out.write("<title>Uuden asiakkaan tiedot</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<form id=\"info\" accept-charset=UTF-8>\r\n");
      out.write("\t<table>\r\n");
      out.write("\t\t<thead>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t<th colspan=\"4\" class=\"right\"><a id=\"back\" href=\"listaaasiakkaat.jsp\">Listaukseen</a></th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t<th>Etunimi</th><th>Sukunimi</th><th>Puhelin</th><th>Sposti</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</thead>\r\n");
      out.write("\t\t<tbody>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t<td><input type=\"text\" name=\"fName\" id=\"fName\"></td>\r\n");
      out.write("\t\t\t<td><input type=\"text\" name=\"lName\" id=\"lName\"></td>\r\n");
      out.write("\t\t\t<td><input type=\"text\" name=\"phone\" id=\"phone\"></td>\r\n");
      out.write("\t\t\t<td><input type=\"text\" name=\"email\" id=\"email\"></td>\r\n");
      out.write("\t\t\t<td><input type=\"button\" name=\"nap\" id=\"tallennus\" value=\"LisÃ¤ys\" onclick=\"lisaaAs()\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</tbody>\r\n");
      out.write("\t</table>\r\n");
      out.write("</form>\r\n");
      out.write("<span id=\"ilmo\"></span>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("function tutkiKey(event){\r\n");
      out.write("\tif(event.keyCode==13){\r\n");
      out.write("\t\tlisaaAs();\r\n");
      out.write("\t}\t\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("document.getElementById(\"fName\").focus(); \r\n");
      out.write("\r\n");
      out.write("function lisaaAs() {\r\n");
      out.write("\tvar ilmo=\"\"; \r\n");
      out.write("\tif(document.getElementById(\"fName\").value.length<2){\r\n");
      out.write("\t\tilmo=\"Nimi ei kelpaa!\";\t\t\r\n");
      out.write("\t}else if(document.getElementById(\"lName\").value.length<2){\r\n");
      out.write("\t\tilmo=\"Nimi ei kelpaa!\";\t\t\r\n");
      out.write("\t}else if(document.getElementById(\"phone\").value.length<5){\r\n");
      out.write("\t\tilmo=\"Puhelinnumero on liian lyhyt!\";\t\t\r\n");
      out.write("\t}else if(document.getElementById(\"email\").value.length<5){\r\n");
      out.write("\t\tilmo=\"Email on liian lyhyt!\";\t\r\n");
      out.write("\t}\r\n");
      out.write("\tif(ilmo!=\"\"){\r\n");
      out.write("\t\tdocument.getElementById(\"ilmo\").innerHTML=ilmo;\r\n");
      out.write("\t\tsetTimeout(function(){ document.getElementById(\"ilmo\").innerHTML=\"\"; }, 3000);\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tdocument.getElementById(\"fName\").value=cleanUp(document.getElementById(\"fName\").value);\r\n");
      out.write("\tdocument.getElementById(\"lName\").value=cleanUp(document.getElementById(\"lName\").value);\r\n");
      out.write("\tdocument.getElementById(\"phone\").value=cleanUp(document.getElementById(\"phone\").value);\r\n");
      out.write("\tdocument.getElementById(\"email\").value=cleanUp(document.getElementById(\"email\").value);\t\r\n");
      out.write("\r\n");
      out.write("\tvar formJsonStr = formDataJsonStr(document.getElementById(\"info\")); \r\n");
      out.write("\t\r\n");
      out.write("\tfetch(\"asiakkaat\", {method: \"POST\", body: formJsonStr})\r\n");
      out.write("\t.then( function (response) {\t\r\n");
      out.write("\t\treturn response.json()\r\n");
      out.write("\t})\r\n");
      out.write("\t.then( function (responseJson) {//Otetaan vastaan objekti responseJson-parametrissï¿½\t\r\n");
      out.write("\t\tvar vastaus = responseJson.response;\t\t\r\n");
      out.write("\t\tif(vastaus==0){\r\n");
      out.write("\t\t\tdocument.getElementById(\"ilmo\").innerHTML=\"Asiakasta ei voitu lisÃ¤tÃ¤.\";\r\n");
      out.write("      \t}else if(vastaus==1){\t        \t\r\n");
      out.write("      \t\tdocument.getElementById(\"ilmo\").innerHTML=\"Asiakas lisÃ¤tty.\";\t\t\t      \t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tsetTimeout(function(){ document.getElementById(\"ilmo\").innerHTML=\"\"; }, 5000);\r\n");
      out.write("\t});\t\r\n");
      out.write("\tdocument.getElementById(\"info\").reset(); //tyhjennetï¿½ï¿½n tiedot -lomake\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
