/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.39
 * Generated at: 2020-12-04 13:24:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class listaaasiakkaat_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/style.css\">\r\n");
      out.write("<title>Liikaa asiakkaita</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<table id=\"lista\">\r\n");
      out.write("\t\t<thead>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t<th colspan=\"5\" class=\"right\"><span id=\"lisaaUusi\">Uusi asiakas</span></th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th class=\"right\" colspan=\"2\">Hakusana:</th>\r\n");
      out.write("\t\t\t<th><input type=\"text\" id=\"term\" size=\"15em\"></th>\r\n");
      out.write("\t\t\t<th class=\"left\" colspan=\"2\"><input type=\"button\" value=\"Hae\" id=\"nappi\"></th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr class=\"left\">\r\n");
      out.write("\t\t\t<th>Etunimi</th>\r\n");
      out.write("\t\t\t<th>Sukunimi</th>\r\n");
      out.write("\t\t\t<th>Puhelin</th>\r\n");
      out.write("\t\t\t<th colspan=\"2\">Sposti</th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t</thead>\r\n");
      out.write("\t\t<tbody>\r\n");
      out.write("\t\t</tbody>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<span id='ilmo'></span>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\t$(\"#lisaaUusi\").click(function() {\r\n");
      out.write("\t\t\tdocument.location=\"lisaaAsiakas.jsp\";\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\tnoudaAs(); \r\n");
      out.write("\t\t$(\"#nappi\").click(function(){\t\t\r\n");
      out.write("\t\t\tnoudaAs();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(document.body).on(\"keydown\", function(event){\r\n");
      out.write("\t\t\t  if(event.which==13){\r\n");
      out.write("\t\t\t\t  noudaAs();\r\n");
      out.write("\t\t\t  }\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\"#term\").focus();\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tfunction noudaAs() {\r\n");
      out.write("\t\t$(\"#lista tbody\").empty(); \r\n");
      out.write("\t\t$.ajax({url:\"asiakkaat/\"+$(\"#term\").val(), type:\"GET\", dataType:\"json\", success:function(result) {\r\n");
      out.write("\t\t\t$.each(result.asiakkaat, function(i, field) {\r\n");
      out.write("\t\t\t\tvar rowStr; \r\n");
      out.write("\t\t\t\trowStr+=\"<tr id='rivi_\"+field.asiakas_id+\"'>\";\r\n");
      out.write("\t\t\t\trowStr+=\"<td>\"+field.etunimi+\"</td>\";\r\n");
      out.write("\t\t\t\trowStr+=\"<td>\"+field.sukunimi+\"</td>\";\r\n");
      out.write("\t\t\t\trowStr+=\"<td>\"+field.puhelin+\"</td>\";\r\n");
      out.write("\t\t\t\trowStr+=\"<td>\"+field.sposti+\"</td>\";\r\n");
      out.write("\t\t\t\trowStr+=\"<td><a href='muutaasiakas.jsp?asiakas_id=\"+field.asiakas_id+\"'>Muuta</a>&nbsp;\";\r\n");
      out.write("\t\t\t\trowStr+=\"<span class='delete' onclick=poista(\"+field.asiakas_id+\",'\"+field.etunimi+\"','\"+field.sukunimi+\"')>Poista</span></td>\";\r\n");
      out.write("\t\t\t\trowStr+=\"</tr>\";\r\n");
      out.write("\t\t\t\t$(\"#lista tbody\").append(rowStr); \r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}});\r\n");
      out.write("\t};\r\n");
      out.write("\t\r\n");
      out.write("\tfunction poista(asiakas_id, etunimi, sukunimi) {\r\n");
      out.write("\t\tif(confirm(\"Poista asiakas \" + etunimi +\" \"+ sukunimi + \"?\")){\r\n");
      out.write("\t\t\t$.ajax({url:\"asiakkaat/\"+asiakas_id, type:\"DELETE\", dataType:\"json\", success:function(result) { //result on joko {\"response:1\"} tai {\"response:0\"}\r\n");
      out.write("\t\t        if(result.response==0){\r\n");
      out.write("\t\t        \t$(\"#ilmo\").html(\"Asiakasta ei voitu poistaa.\");\r\n");
      out.write("\t\t        }else if(result.response==1){\r\n");
      out.write("\t\t        \t$(\"#rivi_\"+asiakas_id).css(\"background-color\", \"red\"); \r\n");
      out.write("\t\t        \talert(\"Asiakkaan \" + asiakas_id +\" poisto onnistui.\");\r\n");
      out.write("\t\t\t\t\tnoudaAs();        \t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t    }});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t};\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
